version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
    depends_on:
      - redis
    container_name: db

  maple:
    build: .
    restart: always
    command: bash -c 'sh /code/maple/bin/docker_start.sh'
    ports:
      - "8000:8000"
    volumes:
      - ./collectedstatic:/code/maple/collectedstatic
      - ./logs:/code/maple/logs
      - ./uploads:/code/maple/uploads
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=maple_user
      - POSTGRES_DB=maple_db
      - POSTGRES_PORT=5432
      - DJANGO_REDIS_URL=redis:6379
    links:
      - db
      - redis
    depends_on:
      - db
    container_name: maple
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./bin/nginx.conf:/etc/nginx/nginx.conf
      - ./collectedstatic:/code/maple/collectedstatic
    links:
      - maple:maple
    container_name: nginx

  redis:
    restart: always
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
